version: "3"
services:
  fake:
    build: .
    volumes:
      - ./src/data_hack_faker/dataclasses:/app/src/data_hack_faker/dataclasses
      - ./src/data_hack_faker/factories:/app/src/data_hack_faker/factories
